### PR TITLE
Kai attendance validation

### PR DESCRIPTION
**Pull request by Kaibanda**

### CODE REVIEW

**Comment by nopivnick** [comment]
@Kaibanda 

@lucia-gomez is not finished with her UI refactor, you shouldn't be merging her work in progress to `main`.

**Comment by Kaibanda** [comment]
@nopivnick I was requesting to merge this with my Branch named "Kai". This is not the main branch, and I worked with Riho to setup a branch I can send pull requests to without merging to main. Thank you.

**Comment by nopivnick** [comment]
@Kaibanda perhaps however I inferred from your comment [here](https://github.com/ITPNYU/mc-reservation-tool/issues/229#issuecomment-2189408382) you intended for that code to then be merged to `main`. I'll drop you a followup email offline.

**Comment by Kaibanda** [comment]
@nopivnick Ok sounds good. I did add a comment in the issue itself 15 minutes ago about referring to the refactorUi branch as the main branch. I will keep this in mind. Thank you for the clarification.

**Pull request closed without merging**
